### PR TITLE
Moved read function to utils, added write function in utils

### PR DESCRIPTION
**Pull request by aaronkho**
Decoupled read and write eqdsk functions from the class. Also provided the eqdsk writer directly from EX2GK.

### CODE REVIEW

**Comment by gsnoep** [comment]
Thanks for your first contribution! Generally the idea is to keep all class related functions in the same class file, utils is only meant for general numerical or pythonic utilities that are useful across different classes.

**Comment by gsnoep** [comment]
I will move the rbbbs and zbbbs reordering so that it starts on the LFS midplane out of the read_geqdsk function soon, thanks for pointing that out!

**Comment by aaronkho** [comment]
So I've moved the functions back to the class and made them "private". I would merge this branch to `main` before making any changes to the boundary rotation though. This is primarily to avoid merge conflicts later.

**Comment by aaronkho** [comment]
> 
> 
> Thanks for your first contribution! Generally the idea is to keep all class related functions in the same class file, utils is only meant for general numerical or pythonic utilities that are useful across different classes.

Also, yes that makes sense. I misunderstood the purpose of the `utils.py` file.

**Comment by aaronkho** [comment]
The eqdsk read/write is now consolidated into a single function for each. The read function still has the boundary rotation applied, and I advise to remove it and place in the derived section. This improves the unity transformation within the read/write loop.

Another potential issue for this unity transformation is the `xdum` argument. It occurs 5 times in the format, but the labels only allow it to be stored as a single number. In principle, an eqdsk can have 5 different numbers in these locations and not affect its validity, but the read/write loop will be unable to recreate it exactly.

**Comment by aaronkho** [comment]
Additionally, please consider using the `@property` decorator for the internal dictionary variables. This allows you to print out `raw` (etc) without the need for the `just_raw` (etc) flags. Here is a sample snippet:
```
@property
def raw(self):
    return self.raw
```

**Comment by aaronkho** [comment]
I also took the liberty to semi-generalize the write function. It does not allow custom format yet, but does allow custom `max_values`.

**Comment by gsnoep** [comment]
I cherrypicked the modifications we wanted from this branch manually and merged the functionality into main in commit 33d5781d83ea4dce96bd303557735df8e949bd6e, so I think we can close this PR

**Pull request closed without merging**
